### ISSUE TITLE
regression

### ISSUE THREAD

**Issue by diraimondo** [P-p-H-d/mlib#32]
Today I updated m-lib on latest commit (2e3b312fab868991895670e901bf0cd17f241d63). I'm not able to compile my project now: it looks related on recent changes on the M_LET macro. Doing some bisect it looks introduced on commit ce948bd9ce7363fab94321e7e83cd4231f6cf1ac where clang started to report the following error:
```
error: array type 'my_tuple_t' (aka 'struct my_tuple_s [1]') is not assignable
                    M_LET(tuple, my_tuple_t) {
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../custom-libs/include/m-core.h:2217:8: note: expanded from macro 'M_LET'
  M_ID(M_LETI1 M_INVERT(a, __VA_ARGS__,                                 \
  ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../custom-libs/include/m-core.h:1082:35: note: expanded from macro 'M_ID'
#define M_ID(...)                 __VA_ARGS__
                                  ^~~~~~~~~~~
../custom-libs/include/m-core.h:2226:3: note: expanded from macro 'M_LETI1'
  M_LETI2(cont, M_GLOBAL_OPLIST(oplist), __VA_ARGS__)
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

The error is unchanged even with current HEAD on git. gcc reports a different message but it should be related to the same problem. 

I hope you can catch the error with the information above; otherwise I can try to reproduce the error on a minimal example.

**Comment by P-p-H-d** [comment]
I was able to regenerate the error with your previous examples.

The problem was identified and, I hope, fixed in master.
Could you confirm the fix?

**Comment by diraimondo** [comment]
Sorry, but the problem is still there for me:
```
error: array type 'my_tuple_t' (aka 'struct my_tuple_s [1]') is not assignable
                    M_LET(tuple, my_tuple_t) {
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../custom-libs/include/m-core.h:2224:8: note: expanded from macro 'M_LET'
  M_ID(M_LETI1 M_INVERT(a, __VA_ARGS__,                                 \
  ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../custom-libs/include/m-core.h:1082:35: note: expanded from macro 'M_ID'
#define M_ID(...)                 __VA_ARGS__
                                  ^~~~~~~~~~~
../custom-libs/include/m-core.h:2233:3: note: expanded from macro 'M_LETI1'
  M_LETI2(cont, M_GLOBAL_OPLIST(oplist), __VA_ARGS__)
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
I can see different line numbers in m-core.h; are they other points to fix?

**Comment by P-p-H-d** [comment]
The different line numbers in m-core is probably due the different in commit https://github.com/P-p-H-d/mlib/commit/ce948bd9ce7363fab94321e7e83cd4231f6cf1ac and master.

Can I have the definition of my_tuple_t and its oplist?

**Comment by P-p-H-d** [comment]
I have pushed more fixed that may explain the issue.

**Comment by diraimondo** [comment]
Ok, these errors are now gone. In two cases they were caused by some my stupid distraction errors in the OPLIST definition. In one case I used a double comma like `TUPLE_OPLIST(name, ONE_OPLIST,, ANOTHER_OPLIST)`, in the other I used `M_CLASSIC_OPLIST` instead of `M_DEFAULT_OPLIST`.
It was stupid but the fact that the pre-processor didn't raise any note and that everything worked great (I mean also at the runtime) until yesterday.... all this didn't help. :-)

After 35 different container definitions such distractions are to be considered...

Thanks for the support.
